from _typeshed import Incomplete
from aiwolf_nlp_common.packet.packet import Packet as Packet

class Client:
    socket: Incomplete
    url: Incomplete
    headers: Incomplete
    def __init__(self, url: str, token: str | None) -> None: ...
    def connect(self) -> None: ...
    def receive(self) -> Packet: ...
    def send(self, req: str) -> None: ...
    def close(self) -> None: ...
