# Generated by datamodel-code-generator from schema/protocol.schema.json in aiwolf-nlp-server. DO NOT EDIT.
# ruff: noqa

from __future__ import annotations

from typing import Any
from msgspec import convert
from dataclasses import dataclass
from enum import StrEnum
from typing import TypeAlias


@dataclass
class Vote:
    day: int
    agent: str
    target: str

    @classmethod
    def from_dict(cls, obj: Any) -> "Vote":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class Talk:
    idx: int
    day: int
    turn: int
    agent: str
    text: str
    skip: bool
    over: bool
    time: int

    @classmethod
    def from_dict(cls, obj: Any) -> "Talk":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class SettingTalkMaxCount:
    per_agent: int
    per_day: int

    @classmethod
    def from_dict(cls, obj: Any) -> "SettingTalkMaxCount":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class SettingTalkMaxLength:
    count_in_word: bool | None = None
    count_spaces: bool | None = None
    per_talk: int | None = None
    mention_length: int | None = None
    per_agent: int | None = None
    base_length: int | None = None

    @classmethod
    def from_dict(cls, obj: Any) -> "SettingTalkMaxLength":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class SettingVote:
    max_count: int
    allow_self_vote: bool

    @classmethod
    def from_dict(cls, obj: Any) -> "SettingVote":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class SettingAttackVote:
    max_count: int
    allow_self_vote: bool
    allow_no_target: bool

    @classmethod
    def from_dict(cls, obj: Any) -> "SettingAttackVote":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class SettingTimeout:
    action: int
    response: int

    @classmethod
    def from_dict(cls, obj: Any) -> "SettingTimeout":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


class Request(StrEnum):
    NAME = 'NAME'
    TALK = 'TALK'
    WHISPER = 'WHISPER'
    VOTE = 'VOTE'
    DIVINE = 'DIVINE'
    GUARD = 'GUARD'
    ATTACK = 'ATTACK'
    INITIALIZE = 'INITIALIZE'
    DAILY_INITIALIZE = 'DAILY_INITIALIZE'
    DAILY_FINISH = 'DAILY_FINISH'
    FINISH = 'FINISH'
    TALK_PHASE_START = 'TALK_PHASE_START'
    TALK_PHASE_END = 'TALK_PHASE_END'
    TALK_BROADCAST = 'TALK_BROADCAST'
    WHISPER_PHASE_START = 'WHISPER_PHASE_START'
    WHISPER_PHASE_END = 'WHISPER_PHASE_END'
    WHISPER_BROADCAST = 'WHISPER_BROADCAST'

    @property
    def require_response(self) -> bool:
        """このリクエストに対してエージェントが応答を返す必要があるか."""
        return {
            Request.NAME: True,
            Request.TALK: True,
            Request.WHISPER: True,
            Request.VOTE: True,
            Request.DIVINE: True,
            Request.GUARD: True,
            Request.ATTACK: True,
            Request.INITIALIZE: False,
            Request.DAILY_INITIALIZE: False,
            Request.DAILY_FINISH: False,
            Request.FINISH: False,
            Request.TALK_PHASE_START: False,
            Request.TALK_PHASE_END: False,
            Request.TALK_BROADCAST: False,
            Request.WHISPER_PHASE_START: False,
            Request.WHISPER_PHASE_END: False,
            Request.WHISPER_BROADCAST: False,
        }[self]


class Role(StrEnum):
    WEREWOLF = 'WEREWOLF'
    POSSESSED = 'POSSESSED'
    SEER = 'SEER'
    BODYGUARD = 'BODYGUARD'
    VILLAGER = 'VILLAGER'
    MEDIUM = 'MEDIUM'

    @property
    def team(self) -> Team:
        """この役職が属する陣営."""
        return {
            Role.WEREWOLF: Team.WEREWOLF,
            Role.POSSESSED: Team.WEREWOLF,
            Role.SEER: Team.VILLAGER,
            Role.BODYGUARD: Team.VILLAGER,
            Role.VILLAGER: Team.VILLAGER,
            Role.MEDIUM: Team.VILLAGER,
        }[self]

    @property
    def species(self) -> Species:
        """この役職の種族."""
        return {
            Role.WEREWOLF: Species.WEREWOLF,
            Role.POSSESSED: Species.HUMAN,
            Role.SEER: Species.HUMAN,
            Role.BODYGUARD: Species.HUMAN,
            Role.VILLAGER: Species.HUMAN,
            Role.MEDIUM: Species.HUMAN,
        }[self]


class Species(StrEnum):
    HUMAN = 'HUMAN'
    WEREWOLF = 'WEREWOLF'


class Team(StrEnum):
    VILLAGER = 'VILLAGER'
    WEREWOLF = 'WEREWOLF'


class Status(StrEnum):
    ALIVE = 'ALIVE'
    DEAD = 'DEAD'


@dataclass
class Judge:
    day: int
    agent: str
    target: str
    result: Species

    @classmethod
    def from_dict(cls, obj: Any) -> "Judge":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class SettingTalk:
    max_count: SettingTalkMaxCount
    max_length: SettingTalkMaxLength
    max_skip: int
    duration: int | None = None

    @classmethod
    def from_dict(cls, obj: Any) -> "SettingTalk":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class Info:
    game_id: str
    day: int
    agent: str
    status_map: dict[str, Status]
    role_map: dict[str, Role]
    profile: str | None = None
    medium_result: Judge | None = None
    divine_result: Judge | None = None
    executed_agent: str | None = None
    attacked_agent: str | None = None
    vote_list: list[Vote] | None = None
    attack_vote_list: list[Vote] | None = None
    remain_count: int | None = None
    remain_length: int | None = None
    remain_skip: int | None = None

    @classmethod
    def from_dict(cls, obj: Any) -> "Info":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class Setting:
    agent_count: int
    role_num_map: dict[str, int]
    vote_visibility: bool
    talk: SettingTalk
    whisper: SettingTalk
    vote: SettingVote
    attack_vote: SettingAttackVote
    timeout: SettingTimeout
    max_day: int | None = None

    @classmethod
    def from_dict(cls, obj: Any) -> "Setting":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


@dataclass
class Packet:
    request: Request
    info: Info | None = None
    setting: Setting | None = None
    talk_history: list[Talk] | None = None
    whisper_history: list[Talk] | None = None
    new_talk: Talk | None = None
    new_whisper: Talk | None = None

    @classmethod
    def from_dict(cls, obj: Any) -> "Packet":
        """辞書からこの構造体を組み立てる."""
        return convert(obj, cls)


AiwolfNlpProtocol: TypeAlias = Packet
